apiVersion: joshault.dev/v1
kind: CREG
metadata:
  name: my-app
  namespace: default
spec:
  cronSpec: '* * * * *'
  image: a string
  replicas: 1
  suspend: true
  readinessProbe:
    path: /readyz
    protocol: https
  labels:
  - name: key
    value: val
