apiVersion: apps/v1
kind: Deployment
metadata:
  name: creg
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: creg
        image: ghcr.io/jault3/creg:v0.0.2
        ports:
        - containerPort: 8080
      serviceAccountName: creg
